azs:
- name: z1
  cpi: openstack-cpi
  cloud_properties:
    availability_zone: nova
- name: z2
  cpi: openstack-cpi
  cloud_properties:
    availability_zone: nova
- name: z3
  cpi: openstack-cpi
  cloud_properties:
    availability_zone: nova

- name: z4
  cpi: vsphere-cpi
  cloud_properties:
    datacenters:
    - clusters:
      - BD-HA:
          resource_pool: BOSH2_PAASTA_40_Pools
      name: BD-HA
- name: z5
  cpi: vsphere-cpi
  cloud_properties:
    datacenters:
    - clusters:
      - BD-HA:
          resource_pool: BOSH2_PAASTA_40_Pools
      name: BD-HA
- name: z6
  cpi: vsphere-cpi
  cloud_properties:
    datacenters:
    - clusters:
      - BD-HA:
          resource_pool: BOSH2_PAASTA_40_Pools
      name: BD-HA

- name: z7
  cpi: openstack-cpi
  cloud_properties:
    availability_zone: nova

vm_types:
- name: minimal
  cloud_properties:
    cpu: 1
    ram: 1024
    disk: 8192
    instance_type: m1.small
- name: default
  cloud_properties:
    cpu: 1
    ram: 2048
    disk: 10240
    instance_type: m1.medium
- name: small
  cloud_properties:
    cpu: 1
    ram: 4096
    disk: 20480 #30720
    instance_type: m1.small
- name: medium
  cloud_properties:
    cpu: 2
    ram: 4096
    disk: 20480
    instance_type: m1.medium
- name: medium-memory-8GB
  cloud_properties:
    cpu: 2
    ram: 8192
    disk: 20480
    instance_type: m1.medium
- name: large
  cloud_properties:
    cpu: 4
    ram: 8192
    disk: 20480
    instance_type: m1.large
- name: xlarge
  cloud_properties:
    cpu: 8
    ram: 16384
    disk: 20480
    instance_type: m1.xlarge
- name: small-50GB
  cloud_properties:
    cpu: 2
    ram: 4096
    disk: 51200
    instance_type: m1.medium
- name: small-50GB-ephemeral-disk
  cloud_properties:
    cpu: 2
    ram: 4096
    disk: 51200
    instance_type: m1.medium
- name: small-100GB-ephemeral-disk
  cloud_properties:
    cpu: 4
    ram: 8192
    disk: 102400
    instance_type: m1.large
- name: small-highmem-100GB-ephemeral-disk
  cloud_properties:
    cpu: 4
    ram: 8192
    disk: 102400
    instance_type: m1.large
- name: small-highmem-16GB
  cloud_properties:
    cpu: 8
    ram: 16384
    disk: 102400
    instance_type: m1.xlarge
- name: service_tiny
  cloud_properties:
    cpu: 1
    ram: 256
    disk: 4096
    instance_type: m1.small
- name: service_small
  cloud_properties:
    cpu: 1
    ram: 512
    disk: 4096
    instance_type: m1.small
- name: service_medium
  cloud_properties:
    cpu: 1
    ram: 1024
    disk: 4096
    instance_type: m1.medium
- name: service_medium_1CPU_2G
  cloud_properties:
    cpu: 1
    ram: 2048
    disk: 4096
    instance_type: m1.medium
- name: service_medium_4G
  cloud_properties:
    cpu: 2
    ram: 4096
    disk: 8192
    instance_type: m1.medium
- name: service_medium_2G
  cloud_properties:
    cpu: 2
    ram: 2048
    disk: 10240
    instance_type: m1.medium
- name: portal_tiny
  cloud_properties:
    cpu: 1
    ram: 256
    disk: 4096
    instance_type: m1.small
- name: portal_small
  cloud_properties:
    cpu: 1
    ram: 512
    disk: 4096
    instance_type: m1.small
- name: portal_medium
  cloud_properties:
    cpu: 1
    ram: 1024
    disk: 4096
    instance_type: m1.medium
- name: portal_large
  cloud_properties:
    cpu: 1
    ram: 2048
    disk: 4096
    instance_type: m1.large

compilation:
  az: z1
  network: default
  reuse_compilation_vms: true
  vm_type: large
  workers: 5

disk_types:
- disk_size: 1024
  name: default
- disk_size: 1024
  name: 1GB
- disk_size: 2048
  name: 2GB
- disk_size: 4096
  name: 4GB
- disk_size: 5120
  name: 5GB
- disk_size: 8192
  name: 8GB
- disk_size: 10240
  name: 10GB
- disk_size: 20480
  name: 20GB
- disk_size: 30720
  name: 30GB
- disk_size: 51200
  name: 50GB
- disk_size: 102400
  name: 100GB
- disk_size: 1048576
  name: 1TB
- cloud_properties:
    type: SSD1 
  disk_size: 2000
  name: 2GB_GP2
- cloud_properties:
    type: SSD1 
  disk_size: 5000
  name: 5GB_GP2
- cloud_properties:
    type: SSD1 
  disk_size: 10000
  name: 10GB_GP2
- cloud_properties:
    type: SSD1 
  disk_size: 50000
  name: 50GB_GP2

networks:
- name: default
  subnets:
  - az: z1
    cloud_properties:
      name: random
      net_id: 657712d9-1948-4e6b-96fb-d6164a530dff
      security_groups:
      - paasta2
    dns:
    - 8.8.8.8
    gateway: 10.0.1.1
    range: 10.0.1.0/24
    reserved:
    - 10.0.1.1 - 10.0.1.9
    static:
    - 10.0.1.10 - 10.0.1.120
  - az: z2
    cloud_properties:
      name: random
      net_id: 657712d9-1948-4e6b-96fb-d6164a530dff
      security_groups:
      - paasta2
    dns:
    - 8.8.8.8
    gateway: 10.0.41.1
    range: 10.0.41.0/24
    reserved:
    - 10.0.41.1 - 10.0.41.9
    static:
    - 10.0.41.10 - 10.0.41.120
  - az: z3
    cloud_properties:
      name: random
      net_id: 657712d9-1948-4e6b-96fb-d6164a530dff
      security_groups:
      - paasta2
    dns:
    - 8.8.8.8
    gateway: 10.0.81.1
    range: 10.0.81.0/24
    reserved:
    - 10.0.81.1 - 10.0.81.9
    static:
    - 10.0.81.10 - 10.0.81.120

  - azs: [z4,z5,z6]
    gateway: 20.30.20.23
    dns: [8.8.8.8]
    range: 20.30.0.0/16
    reserved:
      - 20.30.0.0 - 20.30.30.255
      - 20.30.50.0 - 20.30.255.255
    cloud_properties:
      name: "Internal"

  - az: z7
    cloud_properties:
      name: random
      net_id: 657712d9-1948-4e6b-96fb-d6164a530dff
      security_groups:
      - paasta2
    dns:
    - 8.8.8.8
    gateway: 10.0.0.1
    range: 10.0.0.0/24
    reserved:
    - 10.0.0.1 - 10.0.0.9
    static:
    - 10.0.0.10 - 10.0.0.120
  
- name: vip 
  type: vip

vm_extensions:
- cloud_properties:
    ports:
    - host: 3306
  name: mysql-proxy-lb
- name: cf-router-network-properties
- name: cf-tcp-router-network-properties
- name: diego-ssh-proxy-network-properties
- name: cf-haproxy-network-properties 
- cloud_properties:
    ephemeral_disk:
      size: 51200
      type: gp2
  name: small-50GB 
- cloud_properties:
    ephemeral_disk:
      size: 102400
      type: gp2
  name: small-highmem-100GB
- cloud_properties:
    ephemeral_disk:
      size: 51200
      type: gp2
  name: 50GB_ephemeral_disk
- cloud_properties:
    ephemeral_disk:
      size: 102400
      type: gp2
  name: 100GB_ephemeral_disk 
